### ISSUE TITLE
Algorithm 2 outputs out-pf-original instead of out-pf-improved

### ISSUE THREAD

**Issue by perrette** [r-barnes/Barnes2013-Depressions#1]
It is just a typo in priority_flood.cpp

PS: thanks for sharing the code (just trying to figure out why the basins look so straight - looks like a bug at first sight, but I guess should read the paper first)

**Comment by r-barnes** [comment]
Did you figure out why they are so straight? I'm happy to explain, if you would like.

**Comment by perrette** [comment]
Thanks for offering your help. I have not looked too closely at it yet, but still intend to, and will probably dive into it tomorrow. If you can point me to a section or give a hint, this would be most welcome to get started. I also want to figure out what the differences are with [this other approach](https://github.com/pism/regional-tools). As far as the PISM regional tool is concerned, it results in many small basins at the edges that are (wrongly) not connected with the interior. So I could imagine that the straight lines are a way of bridging some kind of gaps / data errors when the flowlines would otherwise get trapped inside / do not verify some quality criterion. Just an a priori idea.

**Comment by r-barnes** [comment]
I am not sure if the paper explains in depth why those appear the way they do. I have another paper available [here](http://dx.doi.org/10.1016/j.cageo.2013.01.009) (let me know if you would like a PDF copy) which treats the subject in more depth.

Essentially, what happens is this: priority-flood (and many other preprocessing techniques for raster DEMs) fills in depressions. This results in a featureless landscape with no local gradients. Since all water must flow to the edge of the DEM at some point, a gradient must be constructed. Priority-flood+Flowdirs does this by pulling all flow directly towards an edge cell of the filled depression. My [other paper](http://dx.doi.org/10.1016/j.cageo.2013.01.009) directs water away from high edges and towards low edges, which results in a different pattern. But both patterns yield geometrically straight lines because there is no elevation information left upon which to build anything. There's no truly correct way of dealing with this issue. Does that make sense?

If you have an interesting problem with hydrographic analysis algorithms, I'd be game for collaborating on a solution, provided a publishable result emerges.

**Comment by r-barnes** [comment]
I've moved the conversation to email, if that's okay with you.
